### ISSUE TITLE
Wrong bit length in 22PFT4000_12.lircd.conf

### ISSUE THREAD

**Issue by cima** [gcassarino/jquery-mobile-Philips-RC6-tv-remote#1]
I have tried to use your file in raspberry and lirc and it complained about Invalid codes. So I have recorded few keys on my own and it turned out that [your bits value](https://github.com/gcassarino/jquery-mobile-Philips-RC6-tv-remote/blob/6ed6ed623a4ca1eae0a5867969b18c5986645165/Backup-lirc-22PFT4000_12.conf#L21) is too short. You have **13 bits** but it suppose to be **21**. I had to first look into lirc code to get the clue.

Just for the record the remote controller for this TV is officially named YKF346-001.

### Steps to reproduce

1. Place file [Backup-lirc-22PFT4000_12.conf](https://github.com/gcassarino/jquery-mobile-Philips-RC6-tv-remote/blob/6ed6ed623a4ca1eae0a5867969b18c5986645165/Backup-lirc-22PFT4000_12.conf) into /etc/lirc/lircd.conf.d/
2. Start/restart the lircd service
e.g. `sudo service lircd restart`
3. see lircd service status
`sudo service lircd status`

### Expected result
_Using remote: Philips_22PFT4000_12_

### Actual result
Log full of
_Invalid code : KEY_XXX_

**Comment by gcassarino** [comment]
Hello.
The RC6 codes were divided into 8 bits of pre_data and 13 of data for a total of 21 bits.
However looking at the source code of lirc I can say that this warning has always existed since the beginning and it is caused by the wrong value of pre_data 0x77 while it should be 0xEFF (13 bits).
Fortunately, lirc runs a sanity check in which corrects the problem and generates the warning.
So the RC6 codes have been split into 13 bits of pre_data, followed by 8 bits of data and the codes of the keys (begin codes section) will be redefined for example:

```
begin remote

  name  Philips_22PFT4000_12_ALT2
  bits           8
  flags RC6|CONST_LENGTH
  eps            30
  aeps          100

  header       2691   868
  one           467   413
  zero          467   413
  pre_data_bits   13
  pre_data       0xEFF
  gap          106894
  min_repeat      2
#  suppress_repeat 2
#  uncomment to suppress unwanted repeats
  toggle_bit_mask 0x10000
  rc6_mask    0x10000

      begin codes
          KEY_REWIND               0xB2
          KEY_REWIND_ALT           0xD4
          KEY_...
```

Or by removing the values of pre_data_bits, pre_data from the configuration file and keeping the format of the keys codes unchanged, it will be possible to use the value 21 bits as in the example:

```
begin remote

  name  Philips_22PFT4000_12_ALT2
  bits           21
  flags RC6|CONST_LENGTH
  eps            30
  aeps          100

  header       2691   868
  one           467   413
  zero          467   413
  gap          106894
  min_repeat      2
#  suppress_repeat 2
#  uncomment to suppress unwanted repeats
  toggle_bit_mask 0x10000
  rc6_mask    0x10000

      begin codes
          KEY_REWIND               0x0FFFB2
          KEY_REWIND_ALT           0x0FFFD4
          KEY_...
```
